




"""
This script was originally AI generated by gemini, after presenting it with the dilemma of choosing total versus group analysis.
Changes were made to implement it properly into the existing framework.

this analysis is a hierarchical model, effectively eliminating the need of making decisions based the number of responses.

"""
import pymc as pm
import numpy as np
import arviz as az


# Example data setup based on your objects:
# Let's assume you have 4 groups. We stack their counts into a matrix.
# Shape: (n_groups, n_categories) -> (4, 7)
# counts_data = np.array([
#     [2, 5, 10, 20, 50, 30, 10],  # Group 0 (High response)
#     [0, 0,  1,  2,  1,  1,  0],  # Group 1 (Low response - will undergo shrinkage)
#     [5, 5, 20, 20, 10,  5,  2],  # Group 2
#     [1, 2,  5, 30, 40, 20,  5]   # Group 3
# ])


def concatenate_counts(*args):
    """
    Takes an arbitrary number of Question objects, extracts their 7-point 
    response counts, and stacks them into a 2D matrix of shape (n_groups, 7).
    """
    # q.counts.values returns the underlying numpy array of counts for categories 1-7
    matrix = np.array([q.counts.values for q in args])
    return matrix


def find_posterior_distribution(
        question_uib,
        question_uibgeophys,
        question_uio,
        question_uit,
        question_unis):
    
    # 1. Stack the counts from the 5 university groups into a (5, 7) matrix
    counts_data = concatenate_counts(
        question_uib,
        question_uibgeophys,
        question_uio,
        question_uit,
        question_unis,
    )

    # Total respondents per group (N) -> vector of length 5
    n_respondents_per_group = counts_data.sum(axis=1) 

    # The 1-7 Likert scale axis
    scale_values = np.array([1, 2, 3, 4, 5, 6, 7])

    # --- Build the Hierarchical Model ---
    with pm.Model() as hierarchical_model:
        
        # 1. Global Hyperprior: Shared organizational tendencies across ALL groups.
        # we choose halfnormal distribution for the alpha parameters,
        # which are the priors for the Dirichlet distribution.
        # alpha mmust be above 0 but can extend infinitely
        alpha = pm.HalfNormal(
            'alpha', 
            sigma=1, # sigma of the halfnormal distribution. choice based on the prior choice made during previous project, with alpha=1
            shape=7 # <- one for each category
        )

        
        # 2. Group-Level Probabilities (Partial Pooling)
        # choose distribution for theta, the distribution of the parameter of the likelihoood
        theta = pm.Dirichlet(
            'theta', 
            a=alpha, # <- prior
            shape=(counts_data.shape[0], 7) # <- (n_groups, n_categories) 
        )

        # 3. Likelihood: Connects theta to your actual survey data matrix
        # the data are produced by a multinomial distribution with parameters theta, whch themselves are dirichlet distributed
        obs = pm.Multinomial(
            'obs', 
            n=n_respondents_per_group, # <- total respondents per group 
            p=theta, # <- group-level probabilities, modelled as Dirichlet
            observed=counts_data # <- the data
        )
        
        # 4. Expected Mean Score per group
        # theta (5, 7) dot scale_values (7,) results in a vector of 5 expected scores
        expected_scores = pm.Deterministic('expected_scores', pm.math.dot(theta, scale_values))
        
        
        # === ADD THIS LINE FOR THE GLOBAL POPULATION MEAN ===
        # Normalize alpha to get global category probabilities, then dot product with scale_values
        # after the MCMC sampling, the alphas form the posterior distribution of the global tendencies, 
        # and we can use them to calculate the population mean score
        # The alphas are drawn from a halfnormal distribution, and are themselves the parameters of the Dirichlet
        # distribution, but after the MCMC have run, they form the general population Dirichlet distribution.
        # The alphas are pseudocounts, so we can divide by the total alphas to get the density.
        population_probabilities = alpha / pm.math.sum(alpha)
        population_mean_score = pm.Deterministic('population_mean_score', pm.math.dot(population_probabilities, scale_values))

        # --- Run the MCMC Simulation ---
        trace = pm.sample(
            draws=2000, 
            tune=1000, 
            target_accept=0.95, 
            nuts_sampler="numpyro", 
            return_inferencedata=True
        )
    # the trace object contain the internal MCMC parameters, which can be accessed by their keys
    return trace